# Generated by Django 5.2.9 on 2026-01-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_aimodel_aiprovider_systemprompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemprompt',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemprompt',
            name='target_type',
            field=models.CharField(choices=[('main_persona', 'Main persona'), ('intent_classifier', 'Intent classifier')], default='main_persona', max_length=50),
        ),
    ]
