# Generated by Django 5.2.9 on 2026-02-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_systemprompt_is_active_systemprompt_target_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemprompt',
            name='target_type',
            field=models.CharField(choices=[('main_persona', 'Main persona'), ('intent_classifier', 'Intent classifier'), ('tool_todoist', 'Todoist')], default='main_persona', max_length=50),
        ),
    ]
