# Generated by Django 5.2.9 on 2026-02-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_systemprompt_target_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='target_type',
            field=models.CharField(choices=[('main_chat', 'Main chat'), ('intent_classifier', 'Intent classifier')], default='main_chat', max_length=50),
        ),
    ]
