# Generated by Django 5.2.9 on 2026-02-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_aimodel_is_active_aimodel_target_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='api_name',
            field=models.CharField(default='gpt-3.5-turbo', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='target_type',
            field=models.CharField(choices=[('main_chat', 'Main chat'), ('intent_classifier', 'Intent classifier'), ('tool_todoist', 'Todoist')], default='main_chat', max_length=50),
        ),
    ]
