# Generated by Django 5.2.9 on 2026-02-03 23:38

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_aimodel_api_name_alter_aimodel_target_type'),
    ]

    operations = [
        VectorExtension()
    ]
