# Generated by Django 5.2.9 on 2026-02-17 19:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_memory'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalityTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromptCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AgentMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=20, unique=True)),
                ('is_default', models.BooleanField(default=False)),
                ('ai_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.aimodel')),
                ('identity_modules', models.ManyToManyField(blank=True, to='chat.identitymodule')),
            ],
        ),
        migrations.CreateModel(
            name='AgentModeTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('agent_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.agentmode')),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.personalitytrait')),
            ],
        ),
        migrations.AddField(
            model_name='agentmode',
            name='personality_traits',
            field=models.ManyToManyField(blank=True, through='chat.AgentModeTrait', to='chat.personalitytrait'),
        ),
        migrations.AddField(
            model_name='identitymodule',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.promptcategory'),
        ),
        migrations.AddConstraint(
            model_name='agentmodetrait',
            constraint=models.UniqueConstraint(fields=('agent_mode', 'trait'), name='unique_agent_mode_trait', violation_error_message='This personality trait is already in this mode.'),
        ),
    ]
