# Generated by Django 5.2.9 on 2026-02-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_identitymodule_personalitytrait_promptcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmode',
            name='context_message_limit',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='agentmode',
            name='max_tool_iteration_limit',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='agentmode',
            name='rag_results_limit',
            field=models.IntegerField(default=3),
        ),
    ]
